# Dockerfile.pub_cpp
FROM counter_base:latest

# Copiar el paquete a /ws/src
COPY counter_publisher_cpp /ws/src/counter_publisher_cpp

# Construir el paquete con colcon
RUN cd /ws && \
    rosdep install --from-paths src --ignore-src -r -y && \
    colcon build --symlink-install --packages-select counter_publisher_cpp

# Configurar entorno ROS
SHELL ["/bin/bash", "-c"]
