FROM ubuntu:24.04

ENV ROS_DISTRO=jazzy

# Herramientas básicas y compilación
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    gnupg \
    lsb-release \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Repositorio ROS 2
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Instalar ROS 2 runtime y dependencias C++/Python mínimas
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-${ROS_DISTRO}-ros-base \
    ros-${ROS_DISTRO}-ament-cmake \
    ros-${ROS_DISTRO}-rclcpp \
    ros-${ROS_DISTRO}-rclpy \
    ros-${ROS_DISTRO}-std-msgs \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    && rm -rf /var/lib/apt/lists/*

# Instalar colcon y rosdep desde pip
RUN python3 -m pip install -U \
    colcon-common-extensions \
    rosdep

# Inicializar rosdep
RUN rosdep init && rosdep update

WORKDIR /ws
SHELL ["/bin/bash", "-c"]
