apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-cpp
  namespace: ros2-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber-cpp
  template:
    metadata:
      labels:
        app: subscriber-cpp
    spec:
      containers:
        - name: subscriber-cpp
          image: 192.168.100.27:5000/counter_subscriber_cpp:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              value: "subscriber_cpp"
            - name: NAMESPACE
              value: "/ros2_demo"
