apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-cpp
  namespace: ros2-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: publisher-cpp
  template:
    metadata:
      labels:
        app: publisher-cpp
    spec:
      containers:
        - name: publisher-cpp
          image: 192.168.100.27:5000/counter_publisher_cpp:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              value: "/ros2_demo"
